### ISSUE TITLE
Support for `prefers-reduced-motion`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/icons-motion#15]
Does this library have built in support for the [`prefers-reduced-motion` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#:~:text=The%20prefers%2Dreduced%2Dmotion%20CSS,non%2Dessential%20motion%20it%20uses.)? This would ensure animations do not run if the user has turned on the setting.

**Comment by tw15egan** [comment]
Instead of toggling this behavior via a prop, which would then have to be developer enabled, we could add a style block at the root of the style package that targets all `SVG` and disables the animation property. Is there a shared class between all the different icons? If so, you could just do something like:

```css
@media (prefers-reduced-motion) {
  .my-shared-class {
    animation: none;
  }
}
```

That way, any user that has the OS level reduced motion a11y setting set will receive this benefit


https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by tw15egan** [comment]
If developers want to turn off all motion, we should provide a way to do that 👍🏻  I would probably just name it something different, so it doesn't get confused with an a11y distinction and that it is a developer choice.

**Comment by tay1orjones** [comment]
Closed via https://github.com/carbon-design-system/icons-motion/pull/32
